services:
  - type: web
    name: fullstack-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://solutionsharnael:solutionsharnael@abucay.fuogn.mongodb.net/Abucay?retryWrites=true&w=majority&appName=Abucay
    plan: free

  - type: web
    name: fullstack-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    plan: free
