services:
  - type: web
    name: fullstack-app
    env: node
    buildCommand: |
      cd client && npm install && npm run build
      cd ../backend && npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://solutionsharnael:solutionsharnael@abucay.fuogn.mongodb.net/Abucay?retryWrites=true&w=majority&appName=Abucay
      - key: PORT
        value: 5000
